<?php
namespace backend\tests\phpunit\models;

use backend\models\Record;
use Yii;

class RecordTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {

    }
    // перед тестом в модели рекорд установить в BlameableBehavior установить 'value'=>1
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        /*for($i=0;$i < 10000;$i++){
            $model = new Record();
            $model->category_id = 1; // проверяем на существование данной категории в таблице Category
            $model->title = 'str-'.$i;
            $model->preview = 'test';
            $model->content = 'test';
            $model->status = 10;
            $model->save();
        }*/
    }

    /**
     * Валидируем заведомо ложные данные
     * @dataProvider data
     */
    public function testNotValidate($category,$title,$preview,$content,$description)
    {
        $model = new Record();
        $model->category_id = $category; // проверяем на существование данной категории в таблице Category
        $model->title = $title;
        $model->preview = $preview;
        $model->content = $content;
        $model->description = $description;
        $this->assertFalse($model->validate(),'validate!');
    }

    public function data() {
        return [
            [[], 'Заголово', 'Превью', 'Контент','description'],
            ['string', 'Заголово', 'Превью', 'Контент','description'],
            [1, 1, 'Превью', 'Контент','description'],
            [1, 'title', 'Превью', [],'description'],
            [1, 'title', 'Превью', 'К',1223],
            [1155, 'title', 'Превью', 'Preview','description'], // так как нет такой категории
        ];
    }
}