<?php

namespace frontend\widgets;

use backend\models\Record;
use yii\base\Widget;
use yii\data\ActiveDataProvider;

/**
 * Class AllRecordsWidget
 * @package frontend\widgets
 */
class AllRecordsWidget extends Widget  {
    /**
     *
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function run()
    {
        $records = Record::find()
            ->select(['id','category_id','title','slug','position','preview','status','created_at'])
            ->andWhere(['status'=>10])
            ->with(['category','tagArticles'])
            ->orderBy('position DESC, created_at DESC');

        $dataProvider = new ActiveDataProvider([
            'query' => $records,
            'pagination' => [
                'pageSize' => 5,
                'pageSizeParam' => false,
                'forcePageParam' => false,
                //'route' => 'front/index'
            ],
        ]);

        return $this->render('records_all',['dataProvider'=>$dataProvider]);
    }
}