<?php

namespace frontend\widgets;

use backend\models\Category;
use yii\base\Widget;
use yii\helpers\Html;

class CategoriesWidget extends Widget {

    /**
     * Нормализация свойств виджета
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Результат рендинга виджета
     */
    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        $categories = Category::find()->select(['id','title'])->orderBy('title')->all();
        foreach ($categories as $category) {
            echo Html::tag('p', Html::a($category->title,['/blog/category', 'id' => $category->id], ['class'=>'alert__link']));
        }
    }
}